### ISSUE TITLE
04-11-21 Battlefield update has patched xx4

### ISSUE THREAD

**Issue by ReiIZU** [exex4/xx4-bfv-aimassist#17]
Program is stuck on [+] Locating initial Dx11 key location, please wait...

**Comment by hugoballester78** [comment]
I think is the DX11 secret key that changed

**Comment by 70RMUND** [comment]
Here is the fix to one of the main offsets:

https://github.com/exex4/xx4-bfv-aimassist/pull/18

**Comment by ReiIZU** [comment]
> Here is the fix to one of the main offsets:
> 
> #18

Confirmed working, manually applied to my own offsets.py. Thanks for the quick resolution, hope the pull request gets approved soon.
