### ISSUE TITLE
Add a setting of fov to seek for enemies

### ISSUE THREAD

**Issue by molotovah** [exex4/xx4-bfv-aimassist#2]
Hello , 

Nice work on this release ! It would be great to declare variables so we can set a field of view to seek for enemies because mine is skipping from one to another.

**Comment by exex4** [comment]
Try the fov setting in d95c04d and see how well that works. It's set to a comfortable default now.

**Comment by federov31** [comment]
@exex4 Great release, tried it yesteday and it was working great.
Today , offsets have been updated so it's not working anymore... I've opened an issue to ask @Tormund the new offsets
