### ISSUE TITLE
Hello, do you have an exe file that can be used directly? I don&#039;t know anything. I browse to this post and want to get help very much

### ISSUE THREAD

**Issue by MOU223** [exex4/xx4-bfv-aimassist#7]
[start.bat.txt](https://github.com/exex4/xx4-bfv-aimassist/files/5580881/start.bat.txt)

_Originally posted by @mon5termatt in https://github.com/exex4/xx4-bfv-aimassist/issues/6#issuecomment-731896454_

**Comment by mon5termatt** [comment]
Please remember to delete the .txt from the end of the file

**Comment by MOU223** [comment]
> 请记住从文件.txt中删除文件的文件夹

xx4 aim assist Version 0.4
Thanks to Tormund and jo2305
Using screensize: 1920 x 1080
[+] Searching for BFV.exe
[+] BFV.exe found, Handle 0x28c
[+] Searching for ObfuscationMgr...
[+] Inspecting Thread ID: 0x13d8
[+] Found ObfuscationMgr @ 0x4729ed80
[Head] idle

I didn't change everything in this file. I made exe to run with administrator's permission. What I got was the above description. What's wrong with me? Entering the game has no effect. I hope you can answer it. Please.

xx4 aim assist Version 0.4
Thanks to Tormund and jo2305
Using screensize: 1920 x 1080
[+] Searching for BFV.exe
[+] BFV.exe found, Handle 0x28c
[+] Searching for ObfuscationMgr...
[+] Inspecting Thread ID: 0x13d8
[+] Found ObfuscationMgr @ 0x4729ed80
[+] Inspecting Thread ID: 0x13d8
[+] Locating initial Dx11 key location, please wait...
[+] Found Initial Dx11 key scraping GPU mem @ 0x1bd3d0000
[+] Dynamic key loaded, root key set to 0x5cbe49bd41eec8ce
[+] Dynamic key loaded, root key set to 0x5cbe49bd41eec8ce
[+] Typeinfo: 0x144f2ef50 Encryption Key: 0x547e036625fed445
[+] Found Dx11 key scraping GPU mem @ 0x1bd3d0100
[+] Dynamic key loaded, root key set to 0x1f7b99ff4c56f013
[+] Found Dx11 key scraping GPU mem @ 0x1bd3d0200
[+] Dynamic key loaded, root key set to 0x4e89fde12b829d8f
[Head] idle

**Comment by mon5termatt** [comment]
That output looks fine, there is nothing wrong there

be sure you are hitting the trigger key (LEFT ALT BY DEFAULT)

**Comment by mon5termatt** [comment]
@MOU223 any updates?

**Comment by MOU223** [comment]
> 那个输出看起来不错， 没什么不对的
> 
> 确保您按下了触发器键 （默认的左 Alt）

When I was running the software administrator and the game was running, pressing ALT on the left had no effect. There was no targeting enemy in the game

**Comment by mon5termatt** [comment]
do me a favor and send me the first 39 lines of assist.py from your config

**Comment by MOU223** [comment]
> any updates

No, there is no adjustment in your post code

**Comment by mon5termatt** [comment]
> > any updates
> 
> No, there is no adjustment in your post code

i mean there shouldnt be. that output is normal

**Comment by MOU223** [comment]
> 帮我个忙， 送我前 39 行assist.py你的配置

I'd like to hear more about it, please

**Comment by mon5termatt** [comment]
> > 帮我个忙， 送我前 39 行assist.py你的配置
> 
> I'd like to hear more about it, please

WHAT?

**Comment by MOU223** [comment]
> > > [39] [.py]
> > 
> > 
> > 我想听听更多关于它， 请
> 
> 什么？
This translator is not accurate. Is there any way to contact you on social software

**Comment by mon5termatt** [comment]
i have discord if you have that MON5TERMATT#0001

**Comment by MOU223** [comment]
> > > 帮我个忙， 送我前 39 行assist.py你的配置
> > 
> > 
> > I'd like to hear more about it, please
> 
> WHAT?

What can I do for you?

**Comment by mon5termatt** [comment]
这是正常的。你需要在视线中， 以便它的工作

**Comment by MOU223** [comment]
> 这是正常的。你需要在视线中， 以便它的工作

Do you need the enemy to click ALT on the left again where you can see it

**Comment by mon5termatt** [comment]
hold on

**Comment by MOU223** [comment]
what?

**Comment by mon5termatt** [comment]
https://www.youtube.com/watch?v=rsc1E_S1J4I

**Comment by mon5termatt** [comment]
That is the normal output you should see

**Comment by MOU223** [comment]
I used the file of this post, nothing changed

**Comment by mon5termatt** [comment]
then you are doing something wrong

**Comment by MOU223** [comment]
I don't know. I don't know. I just hope I can get help. Thank you

**Comment by mon5termatt** [comment]
im trying to help, but you aren't listening

**Comment by mon5termatt** [comment]
> xx4 aim assist Version 0.4
> Thanks to Tormund and jo2305
> Using screensize: 1920 x 1080
> [+] Searching for BFV.exe
> [+] BFV.exe found, Handle 0x28c
> [+] Searching for ObfuscationMgr...
> [+] Inspecting Thread ID: 0x13d8
> [+] Found ObfuscationMgr @ 0x4729ed80
> [+] Inspecting Thread ID: 0x13d8
> [+] Locating initial Dx11 key location, please wait...
> [+] Found Initial Dx11 key scraping GPU mem @ 0x1bd3d0000
> [+] Dynamic key loaded, root key set to 0x5cbe49bd41eec8ce
> [+] Dynamic key loaded, root key set to 0x5cbe49bd41eec8ce
> [+] Typeinfo: 0x144f2ef50 Encryption Key: 0x547e036625fed445
> [+] Found Dx11 key scraping GPU mem @ 0x1bd3d0100
> [+] Dynamic key loaded, root key set to 0x1f7b99ff4c56f013
> [+] Found Dx11 key scraping GPU mem @ 0x1bd3d0200
> [+] Dynamic key loaded, root key set to 0x4e89fde12b829d8f
> [Head] idle

# THIS IS NORMAL

**Comment by MOU223** [comment]
> 我试着帮忙， 但你不听

You have misunderstood me. I use the translator to see what you mean. However, access to the Internet is prohibited in China. I will not

**Comment by mon5termatt** [comment]
This script is for multiplayer

**Comment by MOU223** [comment]
> 此脚本用于多人游戏
I used it in BFV multiplayer, but I don't know why it didn't work.

**Comment by mon5termatt** [comment]
i need to go. that script output is normal. make sure your settings are correct...

i use fov 2.5 and no limit

**Comment by MOU223** [comment]
> 我得走了该脚本输出是正常的。请确保您的设置正确...
> 
> 我使用 fov 2.5， 没有限制

Good bye. I'll keep looking for ways. I'll continue to ask for your help later, if you don't mind

**Comment by MOU223** [comment]
> 我得走了该脚本输出是正常的。请确保您的设置正确...
> 
> 我使用 fov 2.5， 没有限制

I saw the video you released. My video output is the same. Press left ALT and it will not aim at the enemy

**Comment by MOU223** [comment]
I saw the video you released. My video output is the same. Press the left alt, it will not aim at the enemy. When you run the program, it will not appear; if you press' y ', it will directly appear all of them

**Comment by MOU223** [comment]
It doesn't target the enemy. It doesn't appear when you run the program; press' y ',

**Comment by MOU223** [comment]
> > xx4 目标辅助版本 0.4感谢 Tormund 和jo2305 使用屏幕： 1920  x 1080 =搜索 Bfv.exe = Bfv.exe 发现， 手柄0x28c = 搜索模糊 mgmr... • 检查线程 ID： 0x13d8  • 找到模糊信息 Mr • 0x4729ed80  • 检查线程 ID： 0x13d8  • 定位初始 Dx11 键位置，请稍候... • 找到初始 Dx11 键刮取 GPU  mem = 0x1bd3d000 = 动态密钥加载，根键设置为 0x5cbe49bd41ec8ce  = 动态键加载， 根密钥设置为 0x5cbe49bd41eec8ce = 类型信息： 0x144f2ef50 加密密钥： 0x547e036625fed445  = 找到 Dx11 密钥刮 Gpu mem =  0x1bd3d0100 = 动态密钥加载， 根键设置为 0x1f7b99ff4c56f013  = 找到 Dx11 键刮取 Gpu mem = 0x1bd3d0200  = 动态密钥加载， 根键设置为 0x4e89fde12b829d8f [头] 空闲
> 
> # 这是正常的

When running the program, it will not appear to press' y ', but will appear directly
xx4 aim assist Version 0.4
Thanks to Tormund and jo2305
Using screensize: 1920 x 1080
[+] Searching for BFV.exe
[+] BFV.exe found, Handle 0x288
[+] Searching for ObfuscationMgr...
[+] Inspecting Thread ID: 0x2b30
[+] Found ObfuscationMgr @ 0x4765ed80
[Head] idle

**Comment by MOU223** [comment]
> 坚持

If you have QQ mailbox, can you give me a try of compressing your program package? Of course, Google mailbox can also be my QQ mailbox :2231725078@qq.com 。
Google email: liuyu223172@gmail.com
