### ISSUE TITLE
Script doesn't work anymore since BF5 update (08-12-2020)

### ISSUE THREAD

**Issue by lukasgodfrey** [exex4/xx4-bfv-aimassist#8]
Hi,

First off, I would like to thank the author of this script. It worked flawlessly until yesterday. I hope there will be an update for this soon!

Again, thank you very much for the hard work!

**Comment by BDarkN** [comment]
Wow Fixed already ! Awesome job bro ! 

Big thank you

**Comment by exex4** [comment]
Fixed in 6a1a136f7d427775cd1828c66291ba56dcbd304d
